build_incident() {

    INCIDENT_COMPONENT="$SERVICE"

    INCIDENT_STATUS="$STATUS"

    INCIDENT_PATTERN_STATE="$PATTERN_STATE"

    INCIDENT_LOG_LEVEL="$LOG_LEVEL"

    INCIDENT_SCORE="$INCIDENT_SCORE"

    INCIDENT_SEVERITY="$INCIDENT_SEVERITY"

    INCIDENT_ERROR_COUNT="$PATTERN_ERROR_COUNT"

    INCIDENT_WARNING_COUNT="$PATTERN_WARNING_COUNT"

    INCIDENT_FAILED_COUNT="$PATTERN_FAILED_COUNT"

    INCIDENT_TIMEOUT_COUNT="$PATTERN_TIMEOUT_COUNT"

    INCIDENT_MATCHED_LINES="$PATTERN_MATCHED_LINES"

    INCIDENT_TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

}